[features]
seeds = false
skip-lint = false
[programs.localnet]
rent_nft = "FQ9MA87E8H8B3aGxnGQwmXNGzgRTap9WL9Yhk3GZT9w8"

[[test.genesis]]
address = "9fQse1hBRfzWweeUod6WEsR4jZf7hVucetEheCaWooY5"
program = "./deps/shadow-nft-standard/target/deploy/shadow_nft_standard.so"

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" # token-2022

# [test.validator]
# url = "https://api.mainnet-beta.solana.com"
[test.validator]
url = "https://swr.xnfts.dev/rpc-proxy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
submodules = "git submodule update --init --recursive && deps/shadow-nft-standard/ && anchor build && cd ../../"
