[features]
seeds = false
skip-lint = false
[programs.localnet]
rent_nft = "FQ9MA87E8H8B3aGxnGQwmXNGzgRTap9WL9Yhk3GZT9w8"

# Shadow NFT Standard Loader
[[test.validator.account]]
address = "9fQse1hBRfzWweeUod6WEsR4jZf7hVucetEheCaWooY5"
filename = "deps/shadow_nft_standard_loader.json"

# Shadow NFT Standard Data Account
[[test.validator.account]]
address = "E3AuyxUidXpTeYh98i8PQs2eoKibjgU184gb6tEELxWH"
filename = "deps/shadow_nft_standard_data.json"

# Token2022 Loader
[[test.validator.account]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
filename = "deps/token2022_loader.json"

[[test.validator.account]]
address = "DoU57AYuPFu2QU514RktNPG22QhApEjnKxnBcu4BHDTY"
filename = "deps/token2022_data.json"

# [test.validator]
# url = "https://api.mainnet-beta.solana.com"
[test.validator]
url = "https://swr.xnfts.dev/rpc-proxy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
submodules = "git submodule update --init --recursive && deps/shadow-nft-standard/ && anchor build && cd ../../"
