cargo-features = ["workspace-inheritance"]

[package]
name = "rent-nft"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "rent_nft"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { workspace = true, features = ["init-if-needed"] }
anchor-spl = { version = "0.27.0", default-features = false, features = [
  "token",
  "associated_token",
] }
solana-program = { workspace = true }
shadow-nft-standard = { git = "https://github.com/GenesysGo/shadow-nft-standard", features = [
  "cpi",
] }
